[global]
error_log = /tmp/php-fpm-error.log

[www]
access.log = /tmp/php-fpm-access.log
catch_workers_output = yes
decorate_workers_output = no
pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 2
pm.max_spare_servers = 4
pm.max_requests = 500
